steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_RECOUP_ACTIONS_BASE_URL=${_VITE_RECOUP_ACTIONS_BASE_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-northeast1-docker.pkg.dev/aegis-live-488416/recoup/recoup-cockpit
  _VITE_RECOUP_ACTIONS_BASE_URL: https://recoup-actions-377323041120.asia-northeast1.run.app
